# Generated by Django 6.0.6 on 2026-06-18 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('reindexed', 'Reindexed after version update')], default='pending', max_length=30)),
                ('collection_name', models.CharField(blank=True, max_length=100)),
                ('chunks_indexed', models.IntegerField(default=0)),
                ('chunks_failed', models.IntegerField(default=0)),
                ('had_version_update', models.BooleanField(default=False)),
                ('embedding_model', models.CharField(default='models/text-embedding-004', max_length=100)),
                ('embedding_dims', models.IntegerField(default=768)),
                ('avg_tokens_per_chunk', models.FloatField(null=True)),
                ('processing_ms', models.IntegerField(null=True)),
                ('rate_limit_waits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'document_indexing_record',
                'indexes': [models.Index(fields=['document_id'], name='document_in_documen_5de9dc_idx'), models.Index(fields=['status'], name='document_in_status_85eeac_idx'), models.Index(fields=['collection_name', 'status'], name='document_in_collect_2f2fd9_idx')],
            },
        ),
    ]
