# Generated by Django 6.0.6 on 2026-06-18 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_indexing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedIndexingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, max_length=255)),
                ('error_message', models.TextField()),
                ('payload', models.JSONField(blank=True, help_text='The chunk payload or metadata that caused the failure, if available', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'document_indexing_failed_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
