# Generated by Django 6.0.6 on 2026-06-16 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_classification', '0002_alter_document_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('strategy_used', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('char_count', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('contains_tables', models.BooleanField(default=False)),
                ('contains_handwriting', models.BooleanField(default=False)),
                ('contains_drawing', models.BooleanField(default=False)),
                ('contains_stamp', models.BooleanField(default=False)),
                ('contains_signature', models.BooleanField(default=False)),
                ('contains_revision_block', models.BooleanField(default=False)),
                ('contains_title_block', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_pages', to='document_classification.document')),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('strategy_used', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('char_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('processing_ms', models.IntegerField()),
                ('has_handwriting', models.BooleanField(default=False)),
                ('handwriting_segments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='document_processing.page')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('TABLE', 'Table'), ('DRAWING', 'Drawing'), ('STAMP', 'Stamp'), ('SIGNATURE', 'Signature'), ('REVISION', 'Revision')], max_length=20)),
                ('raw_data', models.JSONField()),
                ('text_preview', models.CharField(blank=True, max_length=500)),
                ('confidence', models.FloatField()),
                ('sequence_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_contents', to='document_processing.page')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPLITTING', 'Splitting'), ('PROCESSING', 'Processing'), ('AGGREGATING', 'Aggregating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('total_pages', models.IntegerField(default=0)),
                ('processed_pages', models.IntegerField(default=0)),
                ('failed_pages', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('processing_meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='document_classification.document')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='processing_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='document_processing.processingjob'),
        ),
    ]
