# Generated by Django 6.0.6 on 2026-06-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='layers_to_run',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='page',
            name='refinement_level',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('NEEDS_REVIEW', 'Needs Review')], default='PENDING', max_length=20),
        ),
    ]
