# Generated by Django 6.0.6 on 2026-06-18 06:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('doc_number', models.CharField(blank=True, max_length=100)),
                ('revision', models.CharField(blank=True, max_length=20)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('approval_status', models.CharField(blank=True, max_length=30)),
                ('supersedes_doc_id', models.UUIDField(blank=True, null=True)),
                ('superseded_by_id', models.UUIDField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('project_phase', models.CharField(blank=True, max_length=50)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('wbs_code', models.CharField(blank=True, max_length=50)),
                ('package_code', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor_level', models.CharField(blank=True, max_length=50)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('grid_reference', models.CharField(blank=True, max_length=100)),
                ('main_contractor', models.CharField(blank=True, max_length=200)),
                ('sub_contractor', models.CharField(blank=True, max_length=200)),
                ('consultant', models.CharField(blank=True, max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('drawing_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('discipline', models.CharField(blank=True, max_length=30)),
                ('drawing_scale', models.CharField(blank=True, max_length=30)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('trade', models.CharField(blank=True, max_length=30)),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('metadata_confidence', models.FloatField(default=0.0)),
                ('manually_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_metadata',
                'indexes': [models.Index(fields=['document_id'], name='document_me_documen_d933e7_idx'), models.Index(fields=['is_current'], name='document_me_is_curr_ba7093_idx'), models.Index(fields=['project_id'], name='document_me_project_61781b_idx'), models.Index(fields=['drawing_number'], name='document_me_drawing_03b815_idx'), models.Index(fields=['approval_status'], name='document_me_approva_26b1c5_idx'), models.Index(fields=['project_id', 'is_current'], name='document_me_project_7503ed_idx'), models.Index(fields=['project_id', 'doc_number'], name='document_me_project_96b1a4_idx')],
            },
        ),
    ]
