# Generated by Django 6.0.6 on 2026-06-16 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFingerprint',
            fields=[
                ('hash', models.CharField(help_text='SHA256 of file content', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_fingerprints',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt_templates',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('filename', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_path', models.CharField(max_length=1000)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('contract', 'Contract'), ('boq', 'Bill of Quantities'), ('drawing', 'Construction Drawing'), ('specification', 'Specification'), ('rfi', 'Request for Information'), ('change_order', 'Change Order'), ('invoice', 'Invoice'), ('safety', 'Safety Report'), ('inspection', 'Inspection Report'), ('site_log', 'Site Daily Log'), ('vendor_doc', 'Vendor Document'), ('schedule', 'Project Schedule'), ('email', 'Email Correspondence'), ('calc', 'Engineering Calculation'), ('po', 'Purchase Order'), ('unknown', 'Unknown / Needs Review')], default='unknown', max_length=50)),
                ('doc_subtype', models.CharField(blank=True, max_length=100)),
                ('classification_confidence', models.FloatField(blank=True, null=True)),
                ('layout_confidence', models.FloatField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('classifier_used', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued for Processing'), ('classifying', 'Being Classified'), ('classified', 'Classification Complete'), ('ocr_processing', 'OCR in Progress'), ('chunking', 'Chunking in Progress'), ('embedding', 'Embedding in Progress'), ('indexed', 'Fully Indexed'), ('failed', 'Processing Failed'), ('needs_review', 'Needs Human Review')], default='queued', max_length=30)),
                ('has_tables', models.BooleanField(default=False)),
                ('has_images', models.BooleanField(default=False)),
                ('has_drawings', models.BooleanField(default=False)),
                ('has_handwriting', models.BooleanField(default=False)),
                ('contains_stamp', models.BooleanField(default=False)),
                ('contains_signature', models.BooleanField(default=False)),
                ('contains_revision_block', models.BooleanField(default=False)),
                ('contains_title_block', models.BooleanField(default=False)),
                ('contains_grid_reference', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document_classification.documentfingerprint')),
            ],
            options={
                'db_table': 'document_records',
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('latency_seconds', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage', to='document_classification.document')),
            ],
            options={
                'db_table': 'llm_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='document_classification.prompttemplate')),
            ],
            options={
                'db_table': 'prompt_versions',
            },
        ),
        migrations.CreateModel(
            name='DocumentClassificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classifier_name', models.CharField(max_length=100)),
                ('raw_response', models.TextField(blank=True, help_text='Raw JSON or text returned by LLM')),
                ('doc_type_predicted', models.CharField(max_length=50)),
                ('confidence', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_history', to='document_classification.document')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_classification.promptversion')),
            ],
            options={
                'db_table': 'classification_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason why this document requires human review')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'Review in Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='User ID of the reviewer', max_length=100)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='document_classification.document')),
            ],
            options={
                'db_table': 'review_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project_id', 'doc_type'], name='document_re_project_7242a7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='document_re_status_3435f4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='document_re_file_ha_1a2ee5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promptversion',
            unique_together={('template', 'version_number')},
        ),
    ]
