# Generated by Django 6.0.6 on 2026-06-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('boq', 'Bill of Quantities'), ('drawing', 'Construction Drawing'), ('specification', 'Specification'), ('rfi', 'Request for Information'), ('change_order', 'Change Order'), ('invoice', 'Invoice'), ('safety', 'Safety Report'), ('inspection', 'Inspection Report'), ('site_log', 'Site Daily Log'), ('vendor_doc', 'Vendor Document'), ('schedule', 'Project Schedule'), ('email', 'Email Correspondence'), ('calc', 'Engineering Calculation'), ('po', 'Purchase Order'), ('rfp', 'Request for Proposal'), ('unknown', 'Unknown / Needs Review')], default='unknown', max_length=50),
        ),
    ]
