# Generated by Django 6.0.6 on 2026-06-17 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefinedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.UUIDField(db_index=True)),
                ('raw_text', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('refinement_level', models.CharField(max_length=10)),
                ('layers_applied', models.JSONField(default=list)),
                ('quality_before', models.FloatField()),
                ('quality_after', models.FloatField()),
                ('quality_delta', models.FloatField()),
                ('semantic_validation_used', models.BooleanField(default=False)),
                ('passed_quality_gate', models.BooleanField(default=False)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('refinement_flags', models.JSONField(default=list)),
                ('processing_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refined_content',
                'indexes': [models.Index(fields=['page_id'], name='refined_con_page_id_434039_idx'), models.Index(fields=['needs_human_review'], name='refined_con_needs_h_eedb2a_idx'), models.Index(fields=['passed_quality_gate'], name='refined_con_passed__ba85a4_idx')],
            },
        ),
    ]
