# Generated by Django 6.0.6 on 2026-06-17 21:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('doc_type', models.CharField(blank=True, max_length=50)),
                ('total_pages', models.IntegerField(default=0)),
                ('chunked_pages', models.IntegerField(default=0)),
                ('failed_pages', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('strategy_breakdown', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chunking_job',
                'indexes': [models.Index(fields=['document_id'], name='chunking_jo_documen_704aef_idx'), models.Index(fields=['status'], name='chunking_jo_status_ca5f29_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('page_id', models.UUIDField(db_index=True)),
                ('chunk_index', models.IntegerField()),
                ('chunk_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('char_count', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('strategy_used', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunking_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_chunking.chunkingjob')),
            ],
            options={
                'db_table': 'document_chunk',
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['document_id'], name='document_ch_documen_486d48_idx'), models.Index(fields=['page_id'], name='document_ch_page_id_ad4023_idx'), models.Index(fields=['chunk_type'], name='document_ch_chunk_t_d96b3b_idx'), models.Index(fields=['document_id', 'chunk_index'], name='document_ch_documen_a45e27_idx')],
            },
        ),
    ]
