# Generated by Django 6.0.6 on 2026-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_chunking', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='doc_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='revision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
