# Generated by Django 6.0.6 on 2026-06-18 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('user_query', models.TextField()),
                ('generated_answer', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('answer_grounded', models.BooleanField(default=False)),
                ('needs_fallback', models.BooleanField(default=False)),
                ('chunks_used', models.IntegerField(default=0)),
                ('chunk_ids_used', models.JSONField(default=list)),
                ('filter_used', models.JSONField(default=dict)),
                ('stages_completed', models.JSONField(default=list)),
                ('retrieval_ms', models.IntegerField(default=0)),
                ('generation_ms', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='llama-3.1-8b-instant', max_length=100)),
                ('warning_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rag_generation_log',
                'indexes': [models.Index(fields=['project_id'], name='rag_generat_project_56d909_idx'), models.Index(fields=['created_at'], name='rag_generat_created_74cad0_idx'), models.Index(fields=['answer_grounded'], name='rag_generat_answer__9812c5_idx'), models.Index(fields=['project_id', 'created_at'], name='rag_generat_project_55fd25_idx')],
            },
        ),
    ]
