# Generated by Django 6.0.6 on 2026-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationlog',
            name='ragas_faithfulness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationlog',
            name='thumbs_up',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
